[build]
  publish = "."

[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Robots-Tag = "noindex, nofollow"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=60, must-revalidate"
